#
#
# As a user:
#   run `docker-compose up` to run the demo
# if a new version has been release that you wish to try
#   `docker-compose pull` follwed by
#   `docker-compose up`
#
# If you wish to try a specific version:
#   `IMAGE_TAG='aversion' docker-compose up`
#
services:
  coagent-core:
    image: coadotdev/coagent-core:${IMAGE_TAG:-stable}
    ports:
      - "3000:3000"
    environment:
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLICKHOUSE_DATABASE=coagent
      - CLICKHOUSE_USER=coagent
      - CLICKHOUSE_PASSWORD=coagent
      - DATABASE_URL=postgresql://coagent:coagent@postgres:5432/coagent
      - RUST_LOG=${RUST_LOG:-info}
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./coagent_demo_storage:/app/storage
    depends_on:
      clickhouse:
        condition: service_healthy
    pull_policy: if_not_present

  clickhouse:
    image: clickhouse/clickhouse-server:25.6-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: "coagent"
      CLICKHOUSE_PASSWORD: "coagent"
    volumes:
      - .volumes/clickhouse/data:/var/lib/clickhouse
      - ./config/clickhouse/initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--user", "coagent", "--password", "coagent", "--database", "coagent", "--query", "SELECT 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  surrealdb:
    image: surrealdb/surrealdb:v2.3.7
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
    profiles:
      - surrealdb
    entrypoint:
      - /surreal
      - start
      - --user
      - surreal
      - --pass
      - surreal

  init-surrealdb:
    image: coadotdev/coagent-demo-surrealdb-init:latest
    environment:
      - DB_ENDPOINT=http://surrealdb:8000
    profiles:
      - surrealdb
    depends_on:
      surrealdb:
        condition: service_started

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_storage:/root/.ollama
    profiles:
      - local-llm
    entrypoint: [ "/bin/bash", "-c", "ollama serve & sleep 5 && ollama pull all-minilm && ollama pull qwen3:4b && wait" ]

volumes:
  ollama_storage:
